---
title: "Bryce Turner's resume"
author:  Bryce Turner
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: 
      - resume
      - override.css
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: FALSE

#uncomment the following line to get pdf
knit: pagedown::chrome_print
---


```{r sourceClassesAndFunction, echo = FALSE, message = FALSE, warning=FALSE}
setwd("~/personal/resume/")

library(readxl)
library(tidyverse)

# Helpful Tools
# https://towardsdatascience.com/create-your-resume-with-pagedown-package-in-r-123ca6310d52

# https://livefreeordichotomize.com/2019/09/04/building_a_data_driven_cv_with_r/

```

Aside
================================================================================

```{r, echo = FALSE}
personalDetails <- read_excel(path = "00_resumeDetails.xlsx",
                              sheet = "PersonalDetails") %>% 
  pivot_wider(names_from = LineItem, values_from = Value)
```


Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-phone"></i> `r personalDetails$Phone`
- <i class="fa fa-envelope"></i> `r personalDetails$Email`
- <i class="fa fa-linkedin"></i> `r personalDetails$LinkedInURL`
- <i class="fa fa-github"></i> `r personalDetails$GitHubURL`


Skills {#skills}
--------------------------------------------------------------------------------

```{r, results='asis', echo=FALSE}

cat(paste("-", personalDetails$Languages))
cat("\n \n")
cat(paste("-", personalDetails$CoreCompetency1))
cat("\n \n")
cat(paste("-", personalDetails$CoreCompetency2))
cat("\n \n")
cat(paste("-", personalDetails$CoreCompetency3))

```


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

This resume was made with the R package [**pagedown**](https://github.com/rstudio/pagedown). 
The files used to render this page are available on my github.

Last updated on `r Sys.Date()`.


Main
================================================================================

Bryce Turner {#title}
--------------------------------------------------------------------------------

Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------
```{r prepWorkExperience, echo = FALSE}
source("sourceScripts/WorkExperienceDetails.R")

workExperienceBullets <- read_excel("~/personal/resume/00_resumeDetails.xlsx",
                          sheet = "WorkExperienceBullets" )

allExperienceIds <- unique(workExperienceBullets$ExperienceId)
allRenderedBullets <- mapply(FUN = createWorkBulletsFromExcel,
                             experienceId = allExperienceIds,
                             MoreArgs = 
                               list(fullBulletsDataframe = workExperienceBullets))

names(allRenderedBullets) <- allExperienceIds

experienceIdsToDisplay <- seq(3,5)

workExperienceDetails <-
  read_excel(path = "00_resumeDetails.xlsx",
             sheet = "WorkExperienceDetails") %>% 
  arrange(!is.na(EndDateYear),-EndDateYear) %>% 
  filter(ExperienceId %in% experienceIdsToDisplay)

allRenderedWorkExperiences <- 
  mapply(FUN = createWorkExperienceDetail,
         rowNum = 1:nrow(workExperienceDetails),
         MoreArgs = 
           list(dataframe = workExperienceDetails,
                allRenderedBullets = allRenderedBullets)) %>% 
  lapply(X = .,
         FUN = renderWorkExperienceDetailsForResume) %>% 
  unlist
```

```{r, echo = FALSE, results='asis'}
cat(allRenderedWorkExperiences, sep = "\n\n")
```

Projects {data-icon=laptop}
--------------------------------------------------------------------------------
```{r prepProjectDetails, echo = FALSE}
source("sourceScripts/projectDetails.R")
projectBullets <- read_excel("00_resumeDetails.xlsx",
                             sheet = "ProjectsBullets")
allProjectIds <- unique(projectBullets$ProjectId)

allRenderedBullets <- mapply(FUN = createProjectBulletsFromExcel,
                             projectId = allProjectIds,
                             MoreArgs = 
                               list(fullBulletsDataframe = projectBullets))

names(allRenderedBullets) <- allProjectIds

projectIdsToDisplay <- c("2", "3", "4", "5")

projectDetails <- read_excel("00_resumeDetails.xlsx",
                             sheet = "ProjectsDetails") %>% 
   arrange(!is.na(ProjectYear),-ProjectYear) %>% 
  filter(ProjectId %in% projectIdsToDisplay)


allRenderedProjectsExperiences <- 
  mapply(FUN = createProjectExperienceDetail,
         rowNum = 1:nrow(projectDetails),
         MoreArgs = 
           list(dataframe = projectDetails,
                allRenderedBullets = allRenderedBullets)) %>% 
  lapply(X = .,
         FUN = renderProjectExperienceDetailsForResume) %>% 
  unlist
```

```{r, echo = FALSE, results='asis'}
cat(allRenderedProjectsExperiences, sep = "\n\n")
```

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------
```{r prepEducationResumeDetails, echo = FALSE}
source("sourceScripts/EducationDetails.R")

educationDetailsDataframe <- read_excel(path = "00_resumeDetails.xlsx",
                               sheet = "EducationDetails") %>% 
  arrange(!is.na(EndDate),-EndDate) %>% 
  filter(EducationId == 1)


allEducationDetails <- 
  mapply(FUN = createEducationDetailFromExcel,
         rowNum = seq(1, nrow(educationDetailsDataframe)),
         MoreArgs = list(dataframe = educationDetailsDataframe),
         SIMPLIFY = TRUE) %>% 
  lapply(X = .,
         FUN = renderEducationDetailsForResume) %>% 
  unlist

```

```{r, echo = FALSE, results='asis'}
cat(allEducationDetails, sep = "\n\n")
```

